### PR TITLE
#4 Toast message for windows

### PR DESCRIPTION
**Pull request by FarshanAhamed**
@FrancescoBonizzi  Added toast message for windows whenever the process is restarting.

### CODE REVIEW

**Comment by FrancescoBonizzi** [comment]
Hi Ahamed, thanks for the pull request!
I tested, but nothing shows when `ToastService.Notify` is called!

If it does on your system, can you please send a screenshot?

**Comment by FarshanAhamed** [comment]
It is working as expected in my windows pc.

image

**Comment by FrancescoBonizzi** [comment]
You are right, sorry! 
I had the notifications disabled at OS level. 

Thanks again!

**Comment by FarshanAhamed** [comment]
You are welcome.

**Pull request merged**
