### PR TITLE
Add GUI

### PR DESCRIPTION
**Pull request by Ipolaski**
Add GUI with configs.
GUI and app work in different threads, which can be closed separately 
Fix nuget conflict, update nugets to last versions.

Needs massive refactoring, but this version is work.

### CODE REVIEW

**Comment by FrancescoBonizzi** [comment]
Thanks for your PR. Unfortunately, there are merge conflicts that must be resolved. 
You should sync your fork and merge from main to your current branch. 

Thanks!

**Comment by Ipolaski** [comment]
Conflicts resolved.

**Comment by FrancescoBonizzi** [comment]
Does it build on your machine? 

For example `Configuration` object was previously a record type, now it's a class type, so `JsonFileConfigurationProvider` doesn't compile now.

**Comment by Ipolaski** [comment]
> For example `Configuration` object was previously a record type, now it's a class type, so `JsonFileConfigurationProvider` doesn't compile now.

My bad, didn't notice that part. Now it should build fine.

**Comment by FrancescoBonizzi** [comment]
Perfect. Just a last thing, can you please a screenshot to the GUI in the README.md please?

**Comment by Ipolaski** [comment]
README.md updated

And a small remark:
If you use a record, it is not meant to be used with "with". You should also use {get; init} to prevent this object from being modified.
In your case, it is better to use a class.

**Comment by FrancescoBonizzi** [comment]
Thanks for the suggestion. I managed to fix that.
I also refactored your code to meet with the project conventions. Please run the application and let me know If it's running as expected.

Thanks.

**Comment by Ipolaski** [comment]
Tested it. Looks like working fine.

**Pull request merged**
